algorandfoundation/specs

- dev/Makefile
Otherwise running make under dev in a clean checkout fails because pdf
and html directories don't exist yet.
> fix makefile rules to create directory first

- dev/ledger.md
This PR updates the asset specification as follows:
- There is a new field within each asset's parameters to specify the divisibility of the asset as a power of 10. For example, an asset used for transacting in US Dollars might have this field set to 2 in order to indicate that a single unit of the asset is worth 1 cent.
> Add asset "decimals" field

- dev/ledger.md
Proposers may now specify the delay (in rounds) between accepting a protocol and
executing it.  A flexible delay allows certain upgrades to the protocol (e.g.,
relating to security) to execute faster than others (e.g., relating to new
features).
This delay must fall between some minimum and maximum value.  This change sets
minimum and maximum delay values to be 10,000 and 150,000 rounds, respectively.
Note that this change does not modify the number of votes needed to approve a
upgrade in the first place.
A reference Go implementation may be found here:
https://github.com/algorand/go-algorand/commit/7a415e4855558e66b55785b8342f4e59cb60a2ec
> Give upgrades a flexible delay between acceptance and execution.

- dev/ledger.md
The feature gives balance records a "spending key" field, gives transactions an optional "RekeyTo" address, and gives SignedTxns an optional "authorization address" field. When a transaction rekeys an account, this updates the account's spending key, and future transactions from this account must have their authorization address match (and thus their signatures verify under) this new spending key. This allows rotating spending keys for security while continuing to receive funds at the same address. It also allows changing a normal account into a multisig account (or changing the membership of a multisig account) without changing its address.
This commit also expands the section on transaction signatures to clarify that signatures are not part of transactions (and thus don't influence the …
> [RFC] Add a rekeying feature

- dev/TEAL.md
- dev/TEAL_opcodes.md
- Add versioning to TEAL programs.  Old TEAL program versions remain
supported under version 1.
- Add a #pragma assembler directive for switching between TEAL
program versions.
- Add execution modes to TEAL, with old TEAL programs executed in the
stateless mode.
- Add TEAL version 2, which introduce the changes below.
- Add the ability to access the current TEAL version.
- Add a new stateful execution mode to TEAL, which allows it to
access data resident on chain.  This new mode changes the set of
available opcodes and has different program cost parameters.
- Add opcodes and constants supporting this mode, which include
opcodes to read from on-chain "application" state, opcodes to
read Algo balances, and opcodes to read asset balances.
- Add the ability to read the current round in …
> [RFC] TEAL version 2: manage state, bytes, rekeying, etc.

- dev/TEAL_opcodes.md
* Added a remark about non-existing key deletion (same as #32)
> Make clear values order for opcodes returning multiple values

- dev/abft.md
The number of proposers in the spec doesn't align with the number of proposers we current use in our codebase.
This change update the spec to align with the codebase.
https://github.com/algorand/go-algorand/blob/master/config/consensus.go#L632
> update the NumProposers from 9->20, to reflect current code parameters

- dev/ledger.md
While implementing assets on the indexer I noticed this gap in the spec. This clarifies the metadata stored in an asset holding how the creator holding is in itialized.
> Clarify asset holding and initialization of the creator holding.

- dev/ledger.md
Modify the `LocalDeltas` description to indicate that the intentional content of the `LocalDeltas` is such where empty sets of changes would be omitted from the `ApplyData`.
> Clarify the content of the LocalDeltas

- dev/crypto.md
- dev/ledger.md
This PR describes the specifics of our Merkle tree construction, and describes how that Merkle tree is used to commit to the list of transactions in a block.
> Merkle trees for commitment to the payset in a block

- dev/abft.md
In the Algorand BFT spec section listing conditions for a valid vote, the first invocation of `\Record`:
```
Let $(\pk, B) = (\Record(L, r - \delta_b), I)$,
```
Doesn't match the definition of `\Record` earlier:
```
_Record Lookup_: $\Record(L, r, I_k) = (\pk_{k,r}, B_{k,r})$
```
or other uses of `\Record` later in the spec, such as in the conditions for a valid proposal and a valid seed:
```
Let $(B, \pk) = \Record(L, r - \delta_b, I)$.
...
Let $(B, \pk) = \Record(L, r - \delta_b, I)$; let $q_0 = \Seed(L, r-\delta_s)$.
```
> Fix typo in vote verification conditions

- dev/TEAL.md
- dev/TEAL_opcodes.md
- dev/ledger.md
These are new opcodes to support use-cases such as compiling to TEAL, or more complicated math in AMMs or token bridges.
> 2021 Q2 updates (TEAL4, ASA URL, Program Sizes...)

- dev/abft.md
- dev/ledger.md
This sets the current values of parameters defined in ledger.md to their current values as of the latest consensus version. We plan to change one or more of them in an upcoming update, so establishing their current values in this PR first will make it easier to review those changes.
These values can be found in https://github.com/algorand/go-algorand/blob/master/config/consensus.go
I also updated a typo in the value of $\lambda$ in abft.md to be 2s instead of 4s. The soft/filter timeout has always been 4s, but the language of the abft.md spec uses $2\lambda$ (which would be 8s without this fix) whenever $\lambda$ appears in descriptions of the filter timeout. In the code, a consensus parameter called SmallLambda (2s) and 2*SmallLambda was similarly [originally used to calculate the filter …
> Specify current ledger consensus parameters

- dev/ledger.md
This updates the number of transaction bytes in the block to 5MB (5 * 1024 * 1024 bytes).
> Set block transaction bytes size to 5MB

- dev/ledger.md
A node should be able to accept a lagging state proof transaction at any point in time. Might happen if state proof transaction is delayed.
> StateProofs recoverability

- dev/abft.md
Changes $\lambda_0$ in the consensus spec to match the change in #90.
> abft.md: reduce lambda_0 to 1.5s

- dev/ledger.md
Make the total online stake definition for state proof more precise and mention it excludes expired stake.
> stateproof: update total online stake definition

- dev/abft.md
- dev/crypto.md
- dev/ledger.md
- overview/latex/appendix/ParameterTable.tex
- overview/latex/sections/DetailedConsensus.tex
Update spec for dynamic filter timeout, period 0 deadline timeout, and blockhash in state proof attestment transaction.
> Dynamic Filter Timeout, Period 0 Deadline Timeout, State Proof Blockhash Attestment

- dev/TEAL.md
- dev/ledger.md
Update the specs to reflect the logic size size pooling in transaction groups introduced by this [PR](https://github.com/algorand/go-algorand/pull/6057) to `go-algorand`
> Add logicsig size pooling in transaction groups

- dev/ledger.md
This PR addresses a few minor fixes and typos.
> Minor fixes and typos

- dev/TEAL.md
- dev/TEAL_opcodes.md
- dev/ledger.md
This adds explanations for block incentive payouts, heartbeat transactions, logicsig pooling and AVM v11 opcodes.
> Changes for block incentives and v11 opcodes

- dev/TEAL.md
- dev/TEAL_opcodes.md
- dev/ledger.md
> Typos and payout clarification

- dev/crypto.md
- dev/ledger.md
In https://github.com/algorand/go-algorand/pull/6339 new fields `prev512` and `txn512` were added to the block header. This PR documents these additions, following previous SHA-256 documentation added in https://github.com/algorandfoundation/specs/pull/67
> add description of new SHA-512 usage

- .github/workflows/deploy.yaml
If these artifacts have another use other than deployments, pleast let me know.
> build: no longer fail for outside PRs

- .github/workflows/release.yaml
- docker-compose.yaml
The release artifacts now include just the PDF book, as the HTML is already hosted on the specs website, which could more conveniently be built and served locally with `docker compose up`.
> chore: update release artifacts
